npmPublishAccess: public

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
    '@types/markdown-it@*':
        dependencies:
            'punycode': '*'
            '@types/punycode': '*'
