name: check

on:
    pull_request:
        branches: main

env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 15.x

            - name: install pnpm
              run: npm i pnpm@latest -g
            - name: load cache
              uses: actions/cache@v2
              with:
                  path: |
                      ./.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}
            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER
            - name: install dependencies
              run: pnpm install
            - name: build packs
              run: pnpm build:packs

            - name: run test
              run: |
                  pnpm test

            - name: run cypress
              uses: cypress-io/github-action@v2
              with:
                  install: false
                  start: pnpm start --filter=@milkdown/e2e
                  command: pnpm test --filter=@milkdown/e2e
                  wait-on: 'http://localhost:7000'
                  browser: chrome

            - name: export screenshots (on failure only)
              uses: actions/upload-artifact@v3.0.0
              if: ${{ failure() }}
              with:
                  name: cypress-screenshots
                  path: tests/cypress/screenshots
                  retention-days: 7

            - name: export screen recordings (on failure only)
              uses: actions/upload-artifact@v3.0.0
              if: ${{ failure() }}
              with:
                  name: cypress-videos
                  path: tests/cypress/videos
                  retention-days: 7
