name: Start Agents

on:
  workflow_call:

jobs:
  agents:
    runs-on: ubuntu-latest
    name: Agent
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: load cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}

      - name: install dependencies
        run: pnpm install

      - name: start nx agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
