name: Stop NX Cloud

on:
  workflow_call:

jobs:
  stop-nx-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: load cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install dependencies
        run: pnpm install

      - run: pnpm exec nx-cloud stop-all-agents
