name: Stop NX Cloud

on:
    workflow_call:

jobs:
    stop-nx-cloud:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.6.0

            - uses: pnpm/action-setup@v2.2.3
              with:
                  version: latest
                  run_install: false

            - name: get pnpm store directory
              id: pnpm-cache
              run: |
                  echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - name: load cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}

            - name: install dependencies
              run: pnpm install

            - run: pnpm exec nx-cloud stop-all-agents
