name: Run Test

on:
  workflow_call:
    secrets:
      CYPRESS_RECORD_KEY:
        required: true
      NX_CLOUD_ACCESS_TOKEN:
        required: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0

      - uses: pnpm/action-setup@v2.3.0
        with:
          version: latest
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: load cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install dependencies
        run: pnpm install

      - name: build packs
        run: pnpm build:cache

      - name: run test
        run: pnpm test

  e2e-test:
    needs: unit-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.3.0
        with:
          version: latest
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: load cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install dependencies
        run: pnpm install

      - run: pnpm test:e2e:build

      - name: run cypress on chrome
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_SERVER_PORT: 7000
          CYPRESS_PORT: 8000
        with:
          install: false
          record: true
          parallel: true
          working-directory: e2e
          start: pnpm exec vite preview --host --port 7000
          wait-on: 'http://localhost:7000'
          wait-on-timeout: 120
          browser: chrome
          group: Milkdown-E2E-Chrome
