name: Run Test

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - uses: pnpm/action-setup@v4.0.0
        with:
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: load cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install dependencies
        run: pnpm install

      - name: build packs
        run: pnpm nx affected -t build

      - name: run lint
        run: pnpm test:lint

      - name: run type check
        run: pnpm nx affected -t tsc

  e2e-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: load cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install dependencies
        run: pnpm install

      - run: pnpm test:e2e:build

      - name: run cypress on chrome
        run: pnpm nx affected -t e2e-ci @milkdown/e2e
